# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  webAppName: 'jjloadtestdemo'
  serviceConnection: 'johns'
  azureSubscriptionId: '2e500704-1ab3-49c6-bbbb-8b2bec98ffdc'
  loadTestResource: 'loadtestingpreview'
  loadTestResourceGroup: 'loadtest-rg'
  location: 'North Europe'


stages:
- stage: LoadTest
  displayName: Load Test
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - job: LoadTest
    displayName: Load Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureLoadTest@1
      inputs:
        azureSubscription: $(serviceConnection)
        loadTestConfigFile: 'SampleApp.yaml'
        resourceGroup: $(loadTestResourceGroup)
        loadTestResource: $(loadTestResource)

    - publish: $(System.DefaultWorkingDirectory)/loadTest
      artifact: results
